algoritmo "6"
// Função : recebe a base e a altura do retangulo, calcula e mostra sua area
// Autor : Giovana Ribeiro
// Data : 19/03/2019
// Seção de Declarações 
var
numeroB, numeroA, Res: real

inicio
// Seção de Comandos 
escreval("calcular area do retangulo")
escreval("digite o numeroB")
leia(numeroB)
escreval("digite o numeroA")
leia(numeroA)
Res<-(numeroB * numeroA)
escreva("O resultado é:", Res)


fimalgoritmo
